import { londonTime } from '@/lib/time'
import type { SCAEvent } from '@/types'

/* Weekly sessions, generated rather than listed so the dates can't drift
 * from the pattern. Mirrors the series in the Google Calendar: LeetCode
 * Club on Wednesdays and the SWE project session on Thursdays, both running
 * until the Christmas break (second week of December). */
function weekly(
  slug: string,
  title: string,
  firstDay: string,
  startTime: string,
  endTime: string,
  lastDay: string,
): SCAEvent[] {
  const out: SCAEvent[] = []
  for (let d = new Date(firstDay + 'T00:00:00Z'); d.toISOString().slice(0, 10) <= lastDay; d.setUTCDate(d.getUTCDate() + 7)) {
    const day = d.toISOString().slice(0, 10)
    out.push({
      id: `${slug}-${day}`,
      title,
      description: null,
      location: 'STEAMhouse',
      isOnline: false,
      date: londonTime(`${day}T${startTime}:00`),
      endDate: londonTime(`${day}T${endTime}:00`),
      spots: null,
      registrations: 0,
      registrationUrl: null,
      type: 'WORKSHOP',
      poster: null,
    })
  }
  return out
}

/* The committed event list. Used when Google Calendar sync is not
 * configured or the fetch fails, so the page always has something real to
 * show. Once sync is live this is a safety net, not the source of truth:
 * edit the Google Calendar, not this file. */
export const FALLBACK_EVENTS: SCAEvent[] = [
  {
    id: 'placements-interns-panel-oct-2026',
    title: 'Placements and Interns Panel',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: londonTime('2026-10-02T13:00:00'),
    endDate: londonTime('2026-10-02T14:30:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'PANEL',
    poster: null,
  },
  {
    id: 'placements-interns-roundtable-oct-2026',
    title: 'Placements and Interns Roundtable',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: londonTime('2026-10-12T15:00:00'),
    endDate: londonTime('2026-10-12T16:30:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'PANEL',
    poster: null,
  },
  {
    id: 'career-panel-oct-2026',
    title: 'Career Panel',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: londonTime('2026-10-15T12:00:00'),
    endDate: londonTime('2026-10-15T13:30:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'PANEL',
    poster: null,
  },
  {
    id: 'capture-the-flag-oct-2026',
    title: 'Capture the Flag',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: londonTime('2026-10-23T10:00:00'),
    endDate: londonTime('2026-10-23T16:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'HACKATHON',
    poster: null,
  },
  {
    id: 'fireside-chat-harris-khaliq-oct-2026',
    title: 'Fireside Chat with Cllr. Harris Khaliq',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: londonTime('2026-10-26T17:00:00'),
    endDate: londonTime('2026-10-26T18:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'TALK',
    poster: null,
  },
  {
    id: 'fireside-chat-hamza-hanif-oct-2026',
    title: 'Fireside Chat with Hamza Hanif, Founder and CEO of Sunna Supplements',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: londonTime('2026-10-29T17:30:00'),
    endDate: londonTime('2026-10-29T18:30:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'TALK',
    poster: null,
  },
  {
    id: 'scratch-hackathon-nov-2026',
    title: 'Scratch Hackathon',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: londonTime('2026-11-06T11:00:00'),
    endDate: londonTime('2026-11-06T18:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'HACKATHON',
    poster: null,
  },
  {
    id: 'welcome-week-sept-2026',
    title: 'Welcome Week: Meet the Committee',
    description:
      'Kick off the new academic year with the BCUComputingSoc. Meet the committee, win prizes, and get stuck into a week of fun activities.',
    location: 'STEAMhouse',
    isOnline: false,
    date: londonTime('2026-09-14T12:00:00'),
    endDate: null,
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'NETWORKING',
    poster: null,
  },
  {
    id: 'application-simulation-day-oct-2026',
    title: 'Application Simulation Day',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: londonTime('2026-10-01T09:00:00'),
    endDate: londonTime('2026-10-01T17:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'OTHER',
    poster: null,
  },
  {
    id: 'social-night-june-2026',
    title: 'Social Night: Debate & Gaming',
    description:
      'A collaborative social night with BCU Gaming Society and the Law Debating & Mooting Society. Speed debates on topics from Gaming and AI (12–3 PM), then a relaxed gaming session to meet students from across courses and societies (3–8 PM).',
    location: 'STEAMhouse, CST-302',
    isOnline: false,
    date: londonTime('2026-06-04T12:00:00'),
    endDate: londonTime('2026-06-04T20:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'OTHER',
    poster: '/posters/social-night-june-2026.jpg',
  },
  {
    id: 'placements-interns-panel-cs-2026-09-23',
    title: 'Placements and Interns Panel (CS)',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: londonTime('2026-09-23T17:30:00'),
    endDate: londonTime('2026-09-23T19:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'PANEL',
    poster: null,
  },
  {
    id: 'scratch-hackathon-2026-09-30',
    title: 'Scratch Hackathon',
    description: null,
    location: 'STEAMhouse',
    isOnline: false,
    date: londonTime('2026-09-30T15:00:00'),
    endDate: londonTime('2026-09-30T18:00:00'),
    spots: null,
    registrations: 0,
    registrationUrl: null,
    type: 'HACKATHON',
    poster: null,
  },
  ...weekly('leetcode-club-session', 'LeetCode Club Session (SWE)', '2026-09-23', '13:00', '14:00', '2026-12-09'),
  ...weekly('project-session-swe', 'Project Session (SWE)', '2026-09-24', '13:30', '15:00', '2026-12-10'),
]
